import type { 
  User, 
  Patient, 
  MedicalReport, 
  TimelineEvent, 
  Disease, 
  Medication, 
  LabResult, 
  ChatMessage, 
  DoctorSummary,
  Notification
} from '../types';

export const MOCK_USER: User = {
  id: 'usr_101',
  name: 'Alex Vance',
  email: 'alex.vance@example.com',
  role: 'patient',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=256',
  phoneNumber: '+1 (555) 234-5678',
  preferences: {
    theme: 'dark',
    language: 'English (US)',
    notifications: {
      email: true,
      sms: false,
      criticalAlerts: true,
      aiDigest: true,
    },
    privacy: {
      strictDataIsolation: true,
      localAiProcessingOnly: false,
      auditableLogsEnabled: true,
    },
  },
  createdAt: '2023-01-15T08:30:00Z',
  updatedAt: '2026-08-10T14:20:00Z',
};

export const MOCK_PATIENT: Patient = {
  id: 'pat_909',
  userId: 'usr_101',
  dateOfBirth: '1988-04-12',
  gender: 'male',
  bloodGroup: 'O+',
  heightCm: 178,
  weightKg: 81,
  primaryCarePhysician: 'Dr. Sarah Jenkins, MD (Internal Medicine)',
  emergencyContact: {
    name: 'Elena Vance',
    relationship: 'Spouse',
    phone: '+1 (555) 987-6543',
  },
  insurance: {
    providerName: 'BlueCross HealthCare',
    policyNumber: 'BC-998234-X',
    groupNumber: 'GRP-8812',
    validUntil: '2027-12-31',
  },
  knownAllergies: ['Penicillin (Moderate Rash)', 'Sulfa Drugs (Anaphylaxis Risk)'],
};

export const MOCK_DISEASES: Disease[] = [
  {
    id: 'dis_001',
    name: 'Type 2 Diabetes Mellitus',
    icdCode: 'E11.9',
    status: 'chronic',
    diagnosedDate: '2023-05-14',
    treatingDoctor: 'Dr. Sarah Jenkins, MD',
    sourceReportId: 'rep_005',
    notes: 'Well controlled on Metformin 500mg BID. HbA1c currently 6.7%.',
  },
  {
    id: 'dis_002',
    name: 'Essential Hypertension',
    icdCode: 'I10',
    status: 'active',
    diagnosedDate: '2025-02-10',
    treatingDoctor: 'Dr. Robert Chen, MD',
    sourceReportId: 'rep_007',
    notes: 'Controlled on Lisinopril 10mg QD.',
  },
  {
    id: 'dis_003',
    name: 'Hyperlipidemia (High Cholesterol)',
    icdCode: 'E78.5',
    status: 'active',
    diagnosedDate: '2021-09-18',
    treatingDoctor: 'Dr. Sarah Jenkins, MD',
    sourceReportId: 'rep_003',
    notes: 'Total cholesterol elevated at 242 mg/dL in 2021. Managed with lifestyle modifications.',
  },
  {
    id: 'dis_004',
    name: 'Vitamin D Deficiency',
    icdCode: 'E55.9',
    status: 'resolved',
    diagnosedDate: '2020-11-04',
    resolvedDate: '2021-06-20',
    sourceReportId: 'rep_002',
    notes: 'Vitamin D level restored to 45 ng/mL after Cholecalciferol supplementation.',
  },
  {
    id: 'dis_005',
    name: 'Dengue Fever (Acute)',
    icdCode: 'A90',
    status: 'resolved',
    diagnosedDate: '2019-08-12',
    resolvedDate: '2019-08-28',
    sourceReportId: 'rep_001',
    notes: 'Treated with supportive hydration and monitoring. Full platelet recovery.',
  },
];

export const MOCK_MEDICATIONS: Medication[] = [
  {
    id: 'med_101',
    name: 'Metformin Hydrochloride',
    dosage: '500mg',
    frequency: 'Twice daily with meals',
    route: 'Oral',
    startDate: '2023-05-15',
    status: 'active',
    prescribingDoctor: 'Dr. Sarah Jenkins, MD',
    indication: 'Type 2 Diabetes Mellitus',
    sourceReportId: 'rep_005',
  },
  {
    id: 'med_102',
    name: 'Lisinopril',
    dosage: '10mg',
    frequency: 'Once daily in the morning',
    route: 'Oral',
    startDate: '2025-02-12',
    status: 'active',
    prescribingDoctor: 'Dr. Robert Chen, MD',
    indication: 'Essential Hypertension',
    sourceReportId: 'rep_007',
  },
  {
    id: 'med_103',
    name: 'Atorvastatin Calcium',
    dosage: '10mg',
    frequency: 'Once daily at bedtime',
    route: 'Oral',
    startDate: '2024-03-20',
    status: 'active',
    prescribingDoctor: 'Dr. Sarah Jenkins, MD',
    indication: 'Hyperlipidemia',
    sourceReportId: 'rep_006',
  },
  {
    id: 'med_104',
    name: 'Vitamin D3 (Cholecalciferol)',
    dosage: '60,000 IU',
    frequency: 'Once weekly for 8 weeks',
    route: 'Oral',
    startDate: '2020-11-05',
    endDate: '2021-01-05',
    status: 'completed',
    prescribingDoctor: 'Dr. Michael Chang, MD',
    indication: 'Vitamin D Deficiency',
    sourceReportId: 'rep_002',
  },
];

export const MOCK_LAB_RESULTS: LabResult[] = [
  {
    id: 'lab_201',
    testName: 'Hemoglobin A1c (HbA1c)',
    category: 'metabolic',
    value: 6.7,
    unit: '%',
    referenceRange: '< 5.7%',
    status: 'high',
    testDate: '2026-06-15',
    hospitalName: 'Metro General Hospital',
    sourceReportId: 'rep_008',
  },
  {
    id: 'lab_202',
    testName: 'Fasting Blood Glucose',
    category: 'metabolic',
    value: 128,
    unit: 'mg/dL',
    referenceRange: '70 - 99 mg/dL',
    status: 'high',
    testDate: '2026-06-15',
    hospitalName: 'Metro General Hospital',
    sourceReportId: 'rep_008',
  },
  {
    id: 'lab_203',
    testName: 'Total Cholesterol',
    category: 'lipid_panel',
    value: 198,
    unit: 'mg/dL',
    referenceRange: '< 200 mg/dL',
    status: 'normal',
    testDate: '2026-06-15',
    hospitalName: 'Metro General Hospital',
    sourceReportId: 'rep_008',
  },
  {
    id: 'lab_204',
    testName: 'LDL Cholesterol',
    category: 'lipid_panel',
    value: 112,
    unit: 'mg/dL',
    referenceRange: '< 100 mg/dL',
    status: 'high',
    testDate: '2026-06-15',
    hospitalName: 'Metro General Hospital',
    sourceReportId: 'rep_008',
  },
  {
    id: 'lab_205',
    testName: 'Serum Creatinine',
    category: 'metabolic',
    value: 0.9,
    unit: 'mg/dL',
    referenceRange: '0.7 - 1.3 mg/dL',
    status: 'normal',
    testDate: '2026-06-15',
    hospitalName: 'Metro General Hospital',
    sourceReportId: 'rep_008',
  },
  {
    id: 'lab_206',
    testName: '25-Hydroxy Vitamin D',
    category: 'vitamin',
    value: 48,
    unit: 'ng/mL',
    referenceRange: '30 - 100 ng/mL',
    status: 'normal',
    testDate: '2024-03-18',
    hospitalName: 'Quest Diagnostics',
    sourceReportId: 'rep_006',
  },
];

export const MOCK_REPORTS: MedicalReport[] = [
  {
    id: 'rep_008',
    title: 'Comprehensive Metabolic & Lipid Panel',
    fileName: 'blood_panel_june_2026.pdf',
    fileSize: 2450000,
    fileType: 'application/pdf',
    category: 'blood_report',
    hospitalName: 'Metro General Hospital',
    doctorName: 'Dr. Sarah Jenkins, MD',
    reportDate: '2026-06-15',
    uploadDate: '2026-06-16T09:15:00Z',
    status: 'completed',
    confidenceScore: 0.98,
    rawText: 'Patient: Alex Vance. HbA1c: 6.7%. Fasting Glucose: 128 mg/dL. LDL: 112 mg/dL. Total Cholesterol: 198 mg/dL. Creatinine: 0.9 mg/dL. eGFR > 90 mL/min.',
    summary: 'Shows stable HbA1c control at 6.7%. Lipid panel demonstrates improvement compared to 2021 baseline.',
    extractedEntities: [
      { category: 'lab_value', name: 'HbA1c', value: '6.7', unit: '%', confidence: 0.99 },
      { category: 'lab_value', name: 'Fasting Glucose', value: '128', unit: 'mg/dL', confidence: 0.98 },
      { category: 'disease', name: 'Type 2 Diabetes Mellitus', confidence: 0.95 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_007',
    title: 'Cardiology Evaluation & Blood Pressure Assessment',
    fileName: 'cardio_eval_feb_2025.pdf',
    fileSize: 1890000,
    fileType: 'application/pdf',
    category: 'prescription',
    hospitalName: 'St. Jude Heart Institute',
    doctorName: 'Dr. Robert Chen, MD',
    reportDate: '2025-02-10',
    uploadDate: '2025-02-11T14:30:00Z',
    status: 'completed',
    confidenceScore: 0.96,
    summary: 'Diagnosed Essential Hypertension (BP 142/90 mmHg). Initiated Lisinopril 10mg once daily.',
    extractedEntities: [
      { category: 'disease', name: 'Essential Hypertension', confidence: 0.97 },
      { category: 'medication', name: 'Lisinopril 10mg', confidence: 0.99 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_006',
    title: 'Annual Health Checkup & Lipid Screening',
    fileName: 'annual_checkup_2024.pdf',
    fileSize: 3100000,
    fileType: 'application/pdf',
    category: 'blood_report',
    hospitalName: 'Quest Diagnostics',
    doctorName: 'Dr. Sarah Jenkins, MD',
    reportDate: '2024-03-18',
    uploadDate: '2024-03-19T11:00:00Z',
    status: 'completed',
    confidenceScore: 0.97,
    summary: 'Started low-dose Atorvastatin 10mg for primary prevention of cardiovascular risk.',
    extractedEntities: [
      { category: 'medication', name: 'Atorvastatin 10mg', confidence: 0.98 },
      { category: 'lab_value', name: 'Vitamin D', value: '48', unit: 'ng/mL', confidence: 0.99 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_005',
    title: 'Endocrinology Consultation & Diabetes Diagnosis',
    fileName: 'endo_consult_may_2023.pdf',
    fileSize: 1540000,
    fileType: 'application/pdf',
    category: 'discharge_summary',
    hospitalName: 'Metro General Hospital',
    doctorName: 'Dr. Sarah Jenkins, MD',
    reportDate: '2023-05-14',
    uploadDate: '2023-05-15T16:20:00Z',
    status: 'completed',
    confidenceScore: 0.99,
    summary: 'Confirmed Type 2 Diabetes diagnosis based on HbA1c 7.2%. Prescribed Metformin 500mg BID.',
    extractedEntities: [
      { category: 'disease', name: 'Type 2 Diabetes Mellitus', confidence: 0.99 },
      { category: 'medication', name: 'Metformin 500mg', confidence: 0.99 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_004',
    title: 'Right Knee MRI Scan Report',
    fileName: 'knee_mri_scan_2022.pdf',
    fileSize: 8400000,
    fileType: 'application/pdf',
    category: 'mri',
    hospitalName: 'Apex Imaging & Radiology Center',
    doctorName: 'Dr. Emily Watson, MD (Radiology)',
    reportDate: '2022-09-10',
    uploadDate: '2022-09-12T10:00:00Z',
    status: 'completed',
    confidenceScore: 0.94,
    summary: 'Mild medial meniscus wear. No full-thickness ACL/PCL tears. Normal articular cartilage thickness.',
    extractedEntities: [
      { category: 'procedure', name: 'Right Knee MRI', confidence: 0.99 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_003',
    title: 'Lipid Panel & Cardiovascular Risk Assessment',
    fileName: 'lipid_panel_2021.pdf',
    fileSize: 1200000,
    fileType: 'application/pdf',
    category: 'blood_report',
    hospitalName: 'Quest Diagnostics',
    doctorName: 'Dr. Sarah Jenkins, MD',
    reportDate: '2021-09-18',
    uploadDate: '2021-09-19T08:45:00Z',
    status: 'completed',
    confidenceScore: 0.96,
    summary: 'Elevated total cholesterol (242 mg/dL) and LDL (158 mg/dL). Recommended dietary changes.',
    extractedEntities: [
      { category: 'disease', name: 'Hyperlipidemia', confidence: 0.95 },
      { category: 'lab_value', name: 'Total Cholesterol', value: '242', unit: 'mg/dL', confidence: 0.98 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_002',
    title: 'Vitamin D & Bone Mineral Density Evaluation',
    fileName: 'vitamin_d_report_2020.pdf',
    fileSize: 980000,
    fileType: 'application/pdf',
    category: 'blood_report',
    hospitalName: 'Community Health Lab',
    doctorName: 'Dr. Michael Chang, MD',
    reportDate: '2020-11-04',
    uploadDate: '2020-11-05T13:10:00Z',
    status: 'completed',
    confidenceScore: 0.97,
    summary: 'Severe Vitamin D deficiency detected (14 ng/mL). Prescribed 8-week Cholecalciferol course.',
    extractedEntities: [
      { category: 'disease', name: 'Vitamin D Deficiency', confidence: 0.98 },
      { category: 'medication', name: 'Cholecalciferol 60,000 IU', confidence: 0.99 },
    ],
    fileUrl: '#',
  },
  {
    id: 'rep_001',
    title: 'Dengue Serology & Hospital Discharge Summary',
    fileName: 'dengue_discharge_2019.pdf',
    fileSize: 2150000,
    fileType: 'application/pdf',
    category: 'discharge_summary',
    hospitalName: 'City General Hospital',
    doctorName: 'Dr. Marcus Vance, MD',
    reportDate: '2019-08-12',
    uploadDate: '2019-08-29T15:00:00Z',
    status: 'completed',
    confidenceScore: 0.98,
    summary: 'Admitted for acute Dengue fever with thrombocytopenia. Discharged in stable condition following fluid therapy.',
    extractedEntities: [
      { category: 'disease', name: 'Dengue Fever', confidence: 0.99 },
    ],
    fileUrl: '#',
  },
];

export const MOCK_TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: 'evt_2026_1',
    date: '2026-06-15',
    year: 2026,
    title: 'Follow-up Metabolic & HbA1c Testing',
    description: 'HbA1c recorded at 6.7%, indicating consistent glycemic control. Lipid levels remain stable.',
    type: 'lab_test',
    severity: 'low',
    doctorName: 'Dr. Sarah Jenkins, MD',
    facility: 'Metro General Hospital',
    sourceReportId: 'rep_008',
    sourceReportTitle: 'Comprehensive Metabolic & Lipid Panel',
    connectedEntities: {
      diseases: ['Type 2 Diabetes Mellitus'],
      labResults: ['HbA1c: 6.7%', 'Fasting Glucose: 128 mg/dL'],
    },
  },
  {
    id: 'evt_2025_1',
    date: '2025-02-10',
    year: 2025,
    title: 'Hypertension Diagnosis & Lisinopril Therapy',
    description: 'Blood pressure measured at 142/90 mmHg. Initiated daily Lisinopril 10mg.',
    type: 'diagnosis',
    severity: 'medium',
    doctorName: 'Dr. Robert Chen, MD',
    facility: 'St. Jude Heart Institute',
    sourceReportId: 'rep_007',
    sourceReportTitle: 'Cardiology Evaluation & Blood Pressure Assessment',
    connectedEntities: {
      diseases: ['Essential Hypertension'],
      medications: ['Lisinopril 10mg'],
    },
  },
  {
    id: 'evt_2024_1',
    date: '2024-03-18',
    year: 2024,
    title: 'Atorvastatin Initiated & Normal Vitamin D',
    description: 'Started low-dose statin for cardiovascular prevention. Vitamin D confirmed normal at 48 ng/mL.',
    type: 'medication_start',
    severity: 'low',
    doctorName: 'Dr. Sarah Jenkins, MD',
    facility: 'Quest Diagnostics',
    sourceReportId: 'rep_006',
    sourceReportTitle: 'Annual Health Checkup & Lipid Screening',
    connectedEntities: {
      medications: ['Atorvastatin 10mg'],
      diseases: ['Hyperlipidemia'],
    },
  },
  {
    id: 'evt_2023_1',
    date: '2023-05-14',
    year: 2023,
    title: 'Type 2 Diabetes Diagnosis & Metformin Initiation',
    description: 'Fasting glucose 142 mg/dL and HbA1c 7.2%. Prescribed Metformin 500mg twice daily with meals.',
    type: 'diagnosis',
    severity: 'high',
    doctorName: 'Dr. Sarah Jenkins, MD',
    facility: 'Metro General Hospital',
    sourceReportId: 'rep_005',
    sourceReportTitle: 'Endocrinology Consultation & Diabetes Diagnosis',
    connectedEntities: {
      diseases: ['Type 2 Diabetes Mellitus'],
      medications: ['Metformin 500mg'],
    },
  },
  {
    id: 'evt_2022_1',
    date: '2022-09-10',
    year: 2022,
    title: 'Right Knee MRI Scan',
    description: 'Evaluated right knee joint pain. Revealed mild medial meniscus wear with intact cruciate ligaments.',
    type: 'imaging',
    severity: 'low',
    doctorName: 'Dr. Emily Watson, MD',
    facility: 'Apex Imaging & Radiology Center',
    sourceReportId: 'rep_004',
    sourceReportTitle: 'Right Knee MRI Scan Report',
  },
  {
    id: 'evt_2021_1',
    date: '2021-09-18',
    year: 2021,
    title: 'Hyperlipidemia Identified on Lipid Panel',
    description: 'Total cholesterol reached 242 mg/dL. Commenced therapeutic lifestyle changes and dietary modification.',
    type: 'diagnosis',
    severity: 'medium',
    doctorName: 'Dr. Sarah Jenkins, MD',
    facility: 'Quest Diagnostics',
    sourceReportId: 'rep_003',
    sourceReportTitle: 'Lipid Panel & Cardiovascular Risk Assessment',
    connectedEntities: {
      diseases: ['Hyperlipidemia'],
    },
  },
  {
    id: 'evt_2020_1',
    date: '2020-11-04',
    year: 2020,
    title: 'Severe Vitamin D Deficiency Identified',
    description: 'Serum 25-OH Vitamin D fell to 14 ng/mL. Commenced 8-week high-dose Vitamin D supplementation.',
    type: 'diagnosis',
    severity: 'medium',
    doctorName: 'Dr. Michael Chang, MD',
    facility: 'Community Health Lab',
    sourceReportId: 'rep_002',
    sourceReportTitle: 'Vitamin D & Bone Mineral Density Evaluation',
    connectedEntities: {
      diseases: ['Vitamin D Deficiency'],
      medications: ['Vitamin D3 60,000 IU'],
    },
  },
  {
    id: 'evt_2019_1',
    date: '2019-08-12',
    year: 2019,
    title: 'Acute Dengue Fever Hospitalization',
    description: 'Admitted to City General Hospital for fever and low platelet count (62,000/mcL). Recovered fully after 5 days.',
    type: 'hospital_visit',
    severity: 'critical',
    doctorName: 'Dr. Marcus Vance, MD',
    facility: 'City General Hospital',
    sourceReportId: 'rep_001',
    sourceReportTitle: 'Dengue Serology & Hospital Discharge Summary',
    connectedEntities: {
      diseases: ['Dengue Fever'],
    },
  },
];

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'msg_01',
    sender: 'user',
    text: 'What medicines am I currently taking for diabetes and high blood pressure?',
    timestamp: '10:14 AM',
  },
  {
    id: 'msg_02',
    sender: 'ai',
    text: 'Based on your continuous medical record, you are currently prescribed two active medications for these conditions:\n\n1. **Metformin Hydrochloride (500mg)** - Taken twice daily with meals for **Type 2 Diabetes Mellitus** (started May 15, 2023).\n2. **Lisinopril (10mg)** - Taken once daily in the morning for **Essential Hypertension** (started February 12, 2025).\n\nYour latest lab report from June 15, 2026 shows your HbA1c is 6.7%, indicating steady glycemic control.',
    timestamp: '10:15 AM',
    reasoningType: 'fact',
    citations: [
      {
        reportId: 'rep_008',
        reportTitle: 'Comprehensive Metabolic & Lipid Panel',
        date: '2026-06-15',
        excerpt: 'HbA1c: 6.7%. Metformin 500mg BID continued.',
        confidenceScore: 0.99,
      },
      {
        reportId: 'rep_007',
        reportTitle: 'Cardiology Evaluation & Blood Pressure Assessment',
        date: '2025-02-10',
        excerpt: 'Initiated Lisinopril 10mg QD for Essential Hypertension.',
        confidenceScore: 0.97,
      },
    ],
  },
  {
    id: 'msg_03',
    sender: 'user',
    text: 'When was my highest cholesterol reading recorded?',
    timestamp: '10:18 AM',
  },
  {
    id: 'msg_04',
    sender: 'ai',
    text: 'Your highest recorded cholesterol reading was **242 mg/dL**, logged on **September 18, 2021** in your Quest Diagnostics Lipid Panel.\n\nFollowing that result, you initiated lifestyle modifications, and later started low-dose **Atorvastatin (10mg)** in March 2024. Your most recent panel on June 15, 2026 showed your total cholesterol improved to **198 mg/dL** (Normal range: < 200 mg/dL).',
    timestamp: '10:19 AM',
    reasoningType: 'fact',
    citations: [
      {
        reportId: 'rep_003',
        reportTitle: 'Lipid Panel & Cardiovascular Risk Assessment',
        date: '2021-09-18',
        excerpt: 'Total Cholesterol: 242 mg/dL (High). LDL: 158 mg/dL.',
        confidenceScore: 0.98,
      },
      {
        reportId: 'rep_008',
        reportTitle: 'Comprehensive Metabolic & Lipid Panel',
        date: '2026-06-15',
        excerpt: 'Total Cholesterol: 198 mg/dL (Normal).',
        confidenceScore: 0.99,
      },
    ],
  },
];

export const MOCK_DOCTOR_SUMMARY: DoctorSummary = {
  patientName: 'Alex Vance',
  age: 38,
  gender: 'Male (DOB: 1988-04-12)',
  generatedAt: '2026-08-11T22:00:00Z',
  summaryOverview: '38-year-old male with a history of Type 2 Diabetes Mellitus (HbA1c 6.7%), Essential Hypertension (controlled on Lisinopril), and Hyperlipidemia (managed on Atorvastatin). Resolved history of Dengue fever (2019) and Vitamin D deficiency (2020). Complete longitudinal medical memory verified across 8 connected clinical reports.',
  currentDiseases: MOCK_DISEASES.filter(d => d.status === 'active' || d.status === 'chronic'),
  pastDiseases: MOCK_DISEASES.filter(d => d.status === 'resolved'),
  activeMedications: MOCK_MEDICATIONS.filter(m => m.status === 'active'),
  knownAllergies: MOCK_PATIENT.knownAllergies,
  abnormalLabs: MOCK_LAB_RESULTS.filter(l => l.status === 'high' || l.status === 'critical'),
  riskFactors: [
    'Elevated Fasting Glucose (128 mg/dL)',
    'Borderline Elevated LDL (112 mg/dL)',
    'Family history of premature Coronary Artery Disease',
  ],
  recentReports: MOCK_REPORTS.slice(0, 4),
  timelineHighlights: [
    '2019: Hospitalized for acute Dengue Fever (Fully resolved)',
    '2021: Hyperlipidemia diagnosed (Total Cholesterol 242 mg/dL)',
    '2023: Type 2 Diabetes Mellitus diagnosed (HbA1c 7.2%, started Metformin)',
    '2025: Essential Hypertension diagnosed (Started Lisinopril 10mg)',
    '2026: HbA1c improved to 6.7%; Total Cholesterol normalized to 198 mg/dL',
  ],
};

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif_1',
    title: 'Lab Report Processed',
    message: 'Your Comprehensive Metabolic & Lipid Panel from June 15, 2026 was parsed successfully into patient memory.',
    timestamp: '2 hours ago',
    read: false,
    type: 'report_processed',
    actionUrl: '/reports',
  },
  {
    id: 'notif_2',
    title: 'Abnormal Lab Alert',
    message: 'Fasting Blood Glucose was flagged at 128 mg/dL (Reference: 70-99 mg/dL).',
    timestamp: 'Yesterday',
    read: false,
    type: 'abnormal_lab',
    actionUrl: '/reports',
  },
  {
    id: 'notif_3',
    title: 'Longitudinal Timeline Updated',
    message: '2 new timeline events were automatically constructed from your latest hospital upload.',
    timestamp: '3 days ago',
    read: true,
    type: 'system',
    actionUrl: '/timeline',
  },
];
